"use strict";
var i = 1;
var j = 2;
var k = [];
var k = i & j;
var k = i | j;
var k = i;
~j;
var k = i ^ j;
var k = i << j;
var k = i >> j;
var k = i >>> j;
var k = i && j;
var k = i || j;
var k = !(i);
var k = !(j);
console.log(k[0]);
console.log(k[1]);
console.log(k[2]);
console.log(k[3]);
console.log(k[4]);
console.log(k[5]);
console.log(k[6]);
console.log(k[7]);
console.log(k[8]);
console.log(k[9]);
console.log(k[10]);
console.log(k[11]);
console.log(k[12]);
